name: library-system

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/library
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - library-network

  postgres:
    image: postgres:15
    container_name: library-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - library-network

  redis:
    image: redis:7
    container_name: library-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - library-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    container_name: library-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - library-network

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    container_name: library-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    networks:
      - library-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: library-kafka-ui
    ports:
      - "8090:8080"
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - library-network

networks:
  library-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: