###
GET http://localhost:8080/api/books

<> 2025-03-08T141226.200.json
<> 2025-03-08T141218.404.json
<> 2025-03-08T141154.404.json

###
GET http://localhost:8080/actuator/health

###
GET http://localhost:8080/api/books/author?
    author=J.R.R. Tolkien

###
GET http://localhost:8080/api/books/genre?
    genre=pRoGramMinG

###
GET http://localhost:8080/api/books/isbn?
    isbn=9780544003415

###
GET http://localhost:8080/api/books/title?
    title=Moby Dick

###
@id = d0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14
GET http://localhost:8080/api/books/{{id}}

###
GET http://localhost:8080/api/users


###
GET http://localhost:8080/api/users/email?
    email={{$random.alphanumeric(8)}}

###
GET http://localhost:8080/api/users/username?
    username={{$random.alphanumeric(8)}}

###
@id2 = d96eaa1e-fd5a-4812-9fce-153cc41fef0b
GET http://localhost:8080/api/users/{{id2}}

###
GET http://localhost:8080/api/reviews?
    bookId=6e439804-fb6e-4438-8209-f7d2d2f40e3d

###
PUT http://localhost:8080/api/reviews

###
DELETE http://localhost:8080/api/reviews?
    reviewId=d1ceb67e-68e4-4c03-af06-7c4d3d548746

###
GET http://localhost:8080/api/reservations?
    id=527e3135-a3de-4bc1-81be-5a8a37525b5f

<> 2025-03-08T141314.200.json

###
GET http://localhost:8080/api/reservations/book/6e439804-fb6e-4438-8209-f7d2d2f40e3d>

###
DELETE http://localhost:8080/api/reservations/1143ca89-3acf-470f-8b34-dabf4d127279