name: Build and Lint

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y maven

      - name: Build Application
        run: make build

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Checkstyle
        run: sudo apt update && sudo apt install -y checkstyle

      - name: Run Checkstyle
        run: checkstyle -c /google_checks.xml src/**/*.java
